function countNumbers(arr) {
    const tmpArr = arr.map( item => {
        if (!isNaN(Number(item))) {
            console.log(item)
            return item;
        } else if (arr.length === 0 ){
            return 0;
        } else if(item === '' || item === ' ') {
            return "isNaN";
        }
        else {
            return null;
        }
    })
    return tmpArr.filter( i => i !== null)
}
console.log(countNumbers(['qq', '1', '3', '', ' ', '4we'])); // [ undefined, '1', '3', undefined ]
console.log(isNaN("")) // false
console.log(isNaN(Number(""))) // false
console.log(isNaN(Number(" "))) // false
console.log(!Number.isNaN((" "))) // false


// ================ generated by chrome AI
isNaN("hello"); // returns true, because "hello" cannot be converted to a number
Number.isNaN("hello"); // returns false, because "hello" is not strictly NaN

isNaN(NaN); // returns true
Number.isNaN(NaN) // returns true

isNaN(123); // returns false
Number.isNaN(123); // returns false